package at.ltd.command;

import at.ltd.command.NormalCommands.CommandSkill;
import at.ltd.command.NormalCommands.CommandSkillGroup;
import at.ltd.command.NormalCommands.CommandBan;
import at.ltd.command.NormalCommands.CommandBewerben;
import at.ltd.command.NormalCommands.CommandBuildMode;
import at.ltd.command.NormalCommands.CommandClear;
import at.ltd.command.NormalCommands.CommandClearChat;
import at.ltd.command.NormalCommands.CommandCoins;
import at.ltd.command.NormalCommands.CommandGM;
import at.ltd.command.NormalCommands.CommandGiveAmmo;
import at.ltd.command.NormalCommands.CommandGiveRocket;
import at.ltd.command.NormalCommands.CommandGunInfo;
import at.ltd.command.NormalCommands.CommandGuns;
import at.ltd.command.NormalCommands.CommandHellfire;
import at.ltd.command.NormalCommands.CommandHelp;
import at.ltd.command.NormalCommands.CommandItemToString;
import at.ltd.command.NormalCommands.CommandJoin;
import at.ltd.command.NormalCommands.CommandKick;
import at.ltd.command.NormalCommands.CommandLager;
import at.ltd.command.NormalCommands.CommandLeave;
import at.ltd.command.NormalCommands.CommandLoadLevel;
import at.ltd.command.NormalCommands.CommandLoc;
import at.ltd.command.NormalCommands.CommandLocList;
import at.ltd.command.NormalCommands.CommandMapSpawn;
import at.ltd.command.NormalCommands.CommandMaps;
import at.ltd.command.NormalCommands.CommandMe;
import at.ltd.command.NormalCommands.CommandPing;
import at.ltd.command.NormalCommands.CommandPlayerInfo;
import at.ltd.command.NormalCommands.CommandPlugins;
import at.ltd.command.NormalCommands.CommandPos;
import at.ltd.command.NormalCommands.CommandQuestion;
import at.ltd.command.NormalCommands.CommandReload;
import at.ltd.command.NormalCommands.CommandReloadConfig;
import at.ltd.command.NormalCommands.CommandSay;
import at.ltd.command.NormalCommands.CommandSetLevel;
import at.ltd.command.NormalCommands.CommandSetLevelCoins;
import at.ltd.command.NormalCommands.CommandSettings;
import at.ltd.command.NormalCommands.CommandShop;
import at.ltd.command.NormalCommands.CommandShopItem;
import at.ltd.command.NormalCommands.CommandSound;
import at.ltd.command.NormalCommands.CommandSpawn;
import at.ltd.command.NormalCommands.CommandThreadDump;
import at.ltd.command.NormalCommands.CommandStats;
import at.ltd.command.NormalCommands.CommandStatus;
import at.ltd.command.NormalCommands.CommandStopRound;
import at.ltd.command.NormalCommands.CommandStringToItem;
import at.ltd.command.NormalCommands.CommandSuperUser;
import at.ltd.command.NormalCommands.CommandTest;
import at.ltd.command.NormalCommands.CommandTexturepack;
import at.ltd.command.NormalCommands.CommandTimeBan;
import at.ltd.command.NormalCommands.CommandTp;
import at.ltd.command.NormalCommands.CommandTpAll;
import at.ltd.command.NormalCommands.CommandTpHere;
import at.ltd.command.NormalCommands.CommandTrade;
import at.ltd.command.NormalCommands.CommandTs;
import at.ltd.command.NormalCommands.CommandUnbann;
import at.ltd.command.NormalCommands.CommandUpdate;
import at.ltd.command.NormalCommands.CommandMapVote;

public class CommandRegistry {

	public static void reg() {
		CommandManager.register(new CommandPlugins(), "plugins", "pl");
		CommandManager.register(new CommandTrade(), "trade", "tr");
		CommandManager.register(new CommandSpawn(), "spawn", "hub", "lobby", "home", "lb");
		CommandManager.register(new CommandCoins(), "coins", "money", "vault");
		CommandManager.register(new CommandBewerben(), "bewerben");
		CommandManager.register(new CommandShop(), "shop");
		CommandManager.register(new CommandHelp(), "help", "hilfe", "info");
		CommandManager.register(new CommandMapVote(), "mapvote");
		CommandManager.register(new CommandJoin(), "join");
		CommandManager.register(new CommandSay(), "say");
		CommandManager.register(new CommandLager(), "lager");
		CommandManager.register(new CommandBuildMode(), "buildmode");
		CommandManager.register(new CommandMapSpawn(), "setspawns");
		CommandManager.register(new CommandItemToString(), "item");
		CommandManager.register(new CommandStringToItem(), "itemback");
		CommandManager.register(new CommandLoc(), "loc");
		CommandManager.register(new CommandLeave(), "leave");
		CommandManager.register(new CommandUpdate(), "update");
		CommandManager.register(new CommandPos(), "pos");
		CommandManager.register(new CommandPing(), "ping");
		CommandManager.register(new CommandClear(), "clear");
		CommandManager.register(new CommandReload(), "rl", "reload", "stop", "restart");
		CommandManager.register(new CommandStatus(), "status", "st");
		CommandManager.register(new CommandTp(), "teleport", "tp");
		CommandManager.register(new CommandGM(), "gm", "gamemode");
		CommandManager.register(new CommandSound(), "sounds");
		CommandManager.register(new CommandSetLevel(), "setlevel");
		CommandManager.register(new CommandSetLevelCoins(), "setlevelcoins");
		CommandManager.register(new CommandLoadLevel(), "loadlevel");
		CommandManager.register(new CommandTpHere(), "tphere");
		CommandManager.register(new CommandTpAll(), "tpall");
		CommandManager.register(new CommandSuperUser(), "su", "superuser");
		CommandManager.register(new CommandTest(), "test");
		CommandManager.register(new CommandGuns(), "guns");
		CommandManager.register(new CommandGiveAmmo(), "giveammo");
		CommandManager.register(new CommandGiveRocket(), "giverocket");
		CommandManager.register(new CommandMaps(), "maps");
		CommandManager.register(new CommandTimeBan(), "timeban");
		CommandManager.register(new CommandReloadConfig(), "reloadconfig", "rlcf", "configreload");
		CommandManager.register(new CommandHellfire(), "hellfire");
		CommandManager.register(new CommandShopItem(), "shopitem");
		CommandManager.register(new CommandLocList(), "loclist");
		CommandManager.register(new CommandBan(), "ban", "bann");
		CommandManager.register(new CommandClearChat(), "cc", "clearchat");
		CommandManager.register(new CommandKick(), "kick");
		CommandManager.register(new CommandPlayerInfo(), "playerinfo", "pi");
		CommandManager.register(new CommandUnbann(), "unbann", "unban", "pardon", "removeban", "removebann");
		CommandManager.register(new CommandGunInfo(), "gi", "guninfo");
		CommandManager.register(new CommandQuestion(), "?");
		CommandManager.register(new CommandStats(), "stats");
		CommandManager.register(new CommandStopRound(), "stopround");
		CommandManager.register(new CommandMe(), "me");
		CommandManager.register(new CommandTexturepack(), "texturepack");
		CommandManager.register(new CommandThreadDump(), "threaddump", "dumpthread");
		CommandManager.register(new CommandSkill(), "skill");
		CommandManager.register(new CommandTs(), "ts");
		CommandManager.register(new CommandSkillGroup(), "skillgroup");
		CommandManager.register(new CommandSettings(), "settings");
		// CommandManager.register(new CommandFlySpeed(), "flyspeed");
	}

}
